//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialDemo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_s_import
    {
        public string Наименование_услуги { get; set; }
        public string Главное_изображение { get; set; }
        public string Длительность { get; set; }
        public string Стоимость { get; set; }
        public string Действующая_скидка { get; set; }
    }
}
